### ISSUE TITLE
Detection with HTTPS

### ISSUE THREAD

**Issue by darkfrog26** [URL-Detector/URL-Detector#4]
When I use the following URL in a message:
https://techcrunch.com/2019/10/13/ban-facebook-campaign-ads/?utm_medium=TCnewsletter&tpcc=TCdailynewsletter

It does correctly detect the URL, but the URL returned is:
http://techcrunch.com/2019/10/13/ban-facebook-campaign-ads/?utm_medium=TCnewsletter&amp;tpcc=TCdailynewsletter

Apart from the escaping of the ampersand where it shouldn't be, it's also removing the `s` from `https` leaving me with `http`.

**Comment by cohendekel** [comment]
Which version are you using?
Please also specify the exact API you used.

**Comment by darkfrog26** [comment]
Using `0.1.21` from Maven and using `UrlDetectorOptions.HTML`

**Comment by darkfrog26** [comment]
The exact usage is (sorry, Scala):

```scala
val detector = new UrlDetector("Some text: https://techcrunch.com/2019/10/13/ban-facebook-campaign-ads/?utm_medium=TCnewsletter&tpcc=TCdailynewsletter", UrlDetectorOptions.HTML)
val links = detector.detect()

```

**Comment by darkfrog26** [comment]
Strangely, the problem seems to have gone away, but one big complaint I have is that there doesn't appear to be any way to get the original URL source so that I could search and replace it...the URL returned is often modified with a trailing `/` or some other way manipulated.

**Comment by darkfrog26** [comment]
Closing this ticket as I just found `getOriginalUrl`. Sorry for wasting your time. :o
