### ISSUE TITLE
URL detection misses the url scheme

### ISSUE THREAD

**Issue by srinivashariharan87** [URL-Detector/URL-Detector#6]
For a text like below:
`<a href=https://www.w3schools.com>W3Schools</a>`

expected url: https://www.w3schools.com
actual url after normalization: http://www.w3schools.com

Observations
1. If there is no quote after "=", then the parser omits the url scheme (https) and detects the domain www.w3schools.com only
2. If I add a space after the "=", then the parser works fine - detects the "https" url scheme.

**Comment by cohendekel** [comment]
@srinivashariharan87 please specify the version and the exact API you are using
i couldn't reproduce it.

**Comment by srinivashariharan87** [comment]
It's the latest version of this project 0.1.21.
Running following code
`UrlDetector parser = new UrlDetector(testhtml, UrlDetectorOptions.HTML); 
List<Url> found = parser.detect();
for(Url url : found)
{
   System.out.println(url.getOriginalUrl);
}`


Example String: `<a href=https://www.w3schools.com>W3Schools</a>`
Output: www.w3schools.com

Example String  `<a href="https://www.w3schools.com">W3Schools</a>`
Output: https://www.w3schools.com

**Comment by pgalbraith** [comment]
There is a fix in the latest snapshot release, 0.1.23-SNAPSHOT

**Comment by pgalbraith** [comment]
@srinivashariharan87 please confirm release 0.1.23 fixes the issue, and close.

**Comment by srinivashariharan87** [comment]
@pgalbraith  Issue is fixed. Thanks a lot. Sorry for the late response.
